core/urls.py
from django.urls import path
from . import views
from .views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    ProductView,
    #HomeView,
    OrderSummaryView,
    CheckoutView,
    PaymentView,
    menu,
    weekly_menu,
    update_duration,
    OrderSuccess
)

app_name = 'core'

urlpatterns = [
    #path('', HomeView.as_view(), name='home'),
    path('',views.menu),
    path('product/<pk>/', ProductView.as_view(), name='product'),
    path('weekly-menu/<pk>/', weekly_menu, name='weekly-menu'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order_success/', OrderSuccess.as_view(), name='order_success'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('update_duration/<pk>/', update_duration, name='update_duration'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item')
]

urls.py
from os import name
from django.contrib import admin
from django.urls import path,include,re_path
from . import views 

from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from . import settings

admin.site.site_header="Tiffin Time"
admin.site.colorfield="red"

urlpatterns = [
    re_path(r'^jet/', include('jet.urls', 'jet')),
    re_path(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('',views.Indexpage),
    #path('signup',views.Userreg,name="reg"),
    path('login',views.login,name="log"),
    #path('LOGOUT',views.logout,name="logout"),
    path('home', views.Indexpage),
    path('Menu', views.menu),
    path('about',views.About),
    path('icons',views.icons),
    path('codes',views.codes),
    #path('contact',views.contact),
    path('careers',views.careers),
    path('help',views.pwu),
    path('faq',views.faq),
    path('offers',views.offers),
    path('terms',views.terms),
    path('privacy',views.privacy),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('accounts/', include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    #path('contact_us',views.contact_us),
    path('core/', include('core.urls', namespace='core')),

    
   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/customer_template/all_notification.html
{% extends 'customer_template/base_template.html' %}
{% block page_title %}
Customer Notifications
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">


           <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">All Notifications</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="myinput" onkeyup="myFunction()" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table id="myTable" class="table table-hover text-nowrap">
                  <thead>
                    <tr>
                      <th>Notifications</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for notification in notifications %}
                    <tr>
                      <td>{{ notification.message }}</td>
                      <td>{{ notification.created_at }}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
    function myFunction() {
      // Declare variables
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("myInput");
      filter = input.value.toUpperCase();
      table = document.getElementById("myTable");
      tr = table.getElementsByTagName("tr");
    
      // Loop through all table rows, and hide those who don't match the search query
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[0];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
      }
    }
    </script>
{% endblock custom_js %} 

templates/customer_template/base_template.html
{% load static %}
{% load cart_template_tags %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Tiffin Time | Customer Panel  </title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static "plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static "plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static "plugins/jqvmap/jqvmap.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static "plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static "plugins/daterangepicker/daterangepicker.css" %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static "plugins/summernote/summernote-bs4.css" %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    {% block custom_css %}{% endblock custom_css %}

    {% block extra_head %}{% endblock extra_head %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-red navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        
        <a class="nav-link" href="{{request.META.HTTP_REFERER}}">BACK</a>
      </li>
    </ul>
    <h4 style="margin-left: 10px;margin-top: 5px;">Tiffin Time | Hi {{ user.username }}!</h4>
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      
            <li class="nav-item">
                <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                {% if request.user|cart_item_count != 0 %}
                  <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                {% endif %}
                <i class="fas fa-shopping-cart"></i>
                <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                </a>
            </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">
          Logout
        </a>
      </li>
    </ul>

    <!-- Right navbar links -->
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
    {% include 'customer_template/sidebar_template.html' with user=user id=id %}

  <!-- Content Wrapper. Contains page content -->
   <div class="content-wrapper">
       <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">
                {% block page_title %}
                {% endblock page_title %}
            </h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
     {% block main_content %}{% endblock main_content %}

  </div>
  <!-- /.content-wrapper -->
    {% include 'customer_template/footer.html' %}

</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "plugins/jquery-ui/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- ChartJS -->
<script src="{% static "plugins/chart.js/Chart.min.js" %}"></script>
<!-- Sparkline -->
<script src="{% static "plugins/sparklines/sparkline.js" %}"></script>
<!-- JQVMap -->
<script src="{% static "plugins/jqvmap/jquery.vmap.min.js" %}"></script>
<script src="{% static "plugins/jqvmap/maps/jquery.vmap.usa.js" %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "plugins/jquery-knob/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "plugins/moment/moment.min.js" %}"></script>
<script src="{% static "plugins/daterangepicker/daterangepicker.js" %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Summernote -->
<script src="{% static "plugins/summernote/summernote-bs4.min.js" %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "dist/js/adminlte.js" %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static "dist/js/pages/dashboard.js" %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "dist/js/demo.js" %}"></script>

{% block custom_js %}
{% endblock custom_js %}

{% block extra_scripts %}
{% endblock extra_scripts %}

</body>
</html>

templates/customer_template/customer_feedback.html
{% extends 'customer_template/base_template.html' %}
{% block page_title %}
Feedback Message
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
                    <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Leave a Feedback Message</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
               <form action="{% url 'customer_feedback_save' %}" method="post">
                <div class="card-body">

                    {% csrf_token %}
                  <div class="form-group">
                    <label>Feedback Message</label>
                    <textarea class="form-control" rows="6" name="feedback_msg"></textarea>
                  </div>
                   <div class="form-group">
                      {% if messages %}
                         {% include 'messages.html' %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block" id="fetch_student">Leave a Feedback Message</button>
                </div>
               </form>
            </div>

            <!-- /.card -->
           <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Feedback History</h3>
              </div>

               <div class="table">
               <table class="table">
                   <tr>
                       <th>ID</th>
                       <th>Feedback Message</th>
                       <th>Feedback Reply</th>
                   </tr>
                   {% for row in feedback_data %}
                        <tr>
                            <td>{{ row.id }}</td>
                            <td>{{ row.feedback }}</td>
                            <td>{{ row.feedback_reply }}</td>
                        </tr>
                   {% endfor %}
               </table>
               </div>
            </div>



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

templates/customer_template/customer_home_template.html
{% extends 'customer_template/base_template.html' %}
{% block page_title %}

{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
   

    

    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
    $(document).ready(function(){

            var subjects={{ data_name|safe }};
            var data1={{ data1 }};
            var data2={{ data2 }};
            //Data Set for PIE CHart
           var pieData  = {
              labels: [
                  'ABSENT',
                  'PRESENT',
                  'TOTAL'
              ],
              datasets: [
                {
                  data: [{{ attendance_absent }},{{ attendance_present }},{{ total_attendance }}],
                  backgroundColor : ['#f56954', '#00a65a','#ffc107'],
                }
              ]
            }


            //Data Set for Bar Chart
                var areaChartData = {
                  labels  : subjects,
                  datasets: [
                    {
                      label               : 'Present in Class',
                      backgroundColor     : 'rgba(60,141,188,0.9)',
                      borderColor         : 'rgba(60,141,188,0.8)',
                      pointRadius          : false,
                      pointColor          : '#3b8bba',
                      pointStrokeColor    : 'rgba(60,141,188,1)',
                      pointHighlightFill  : '#fff',
                      pointHighlightStroke: 'rgba(60,141,188,1)',
                      data                : data1
                    },
                    {
                      label               : 'Absent in Class',
                      backgroundColor     : 'rgba(210, 214, 222, 1)',
                      borderColor         : 'rgba(210, 214, 222, 1)',
                      pointRadius         : false,
                      pointColor          : 'rgba(210, 214, 222, 1)',
                      pointStrokeColor    : '#c1c7d1',
                      pointHighlightFill  : '#fff',
                      pointHighlightStroke: 'rgba(220,220,220,1)',
                      data                : data2
                    },
                  ]
                }


            var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
            var pieOptions     = {
              maintainAspectRatio : false,
              responsive : true,
            }
            //Create pie or douhnut chart
            // You can switch between pie and douhnut using the method below.
            var pieChart = new Chart(pieChartCanvas, {
              type: 'pie',
              data: pieData,
              options: pieOptions
            });


            var barChartCanvas = $('#barChart').get(0).getContext('2d')
            var barChartData = jQuery.extend(true, {}, areaChartData)
            var temp1 = areaChartData.datasets[0]
            barChartData.datasets[0] = temp1

            var barChartOptions = {
              responsive              : true,
              maintainAspectRatio     : false,
              datasetFill             : false
            }

            var barChart = new Chart(barChartCanvas, {
              type: 'bar',
              data: barChartData,
              options: barChartOptions
            })
    })
</script>

{% endblock custom_js %}

templates/customer_template/customer_profile.html
{% extends 'customer_template/base_template.html' %}
{% block page_title %}
Edit Profile
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Profile</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{% url 'customer_profile_save' %}" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" name="username" value="{{ user.username }}" disabled="disabled">
                  </div>
                  <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" name="username" value="{{ user.email }}" disabled="disabled">
                  </div>
                   <div class="form-group">
                    <label>First Name</label>
                    <input type="text" class="form-control" name="first_name" value="{{ user.first_name }}">
                  </div>
                  <div class="form-group">
                    <label>Last Name</label>
                    <input type="text" class="form-control" name="last_name" value="{{ user.last_name }}">
                  </div>
                   <div class="form-group">
                    <label>Address</label>
                    <input type="text" class="form-control" name="address" value="{{ customer.address }}">
                  </div>
                   <div class="form-group">
                    <label>Change Password?</label>
                    <input type="text" class="form-control" name="password" placeholder="Fill Only If You want to Change Password">
                  </div>
                   <div class="form-group">
                      {% if messages %}
                         {% include 'messages.html' %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block">Save Profile</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

templates/customer_template/footer.html
 <footer class="main-footer">
    <strong></strong>
    <div class="float-right d-none d-sm-inline-block">
      <b></b> 
    </div>
  </footer>

templates/customer_template/order_summary.html
{% extends 'customer_template/base_template.html' %}

{% block main_content %}

<!--<main>-->
    <div class= "container">
    {% if messages %}
                         {% include 'messages.html' %}
                      {% endif %}
        <div class="table-responsive text-nowrap">
    <h3>
        <strong>Your Cart</strong>
    </h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Duration</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.name }}</td>
            <td>
            {% if order_item.item.discount_price %}
                <del>Rs{{ order_item.item.price}}</del> 
                Rs{{ order_item.item.discount_price }}
            {% else %}
               Rs{{ order_item.item.price}}
            {% endif %}

            </td>
            <td>
                <a href="{% url 'core:reduce-quantity-item' order_item.item.pk %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.pk %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
             <form method = "post" action = "{% url 'core:update_duration' order_item.item.pk %}">
               {% csrf_token %}
						<select id="agileinfo_search" name="dropdown" required="" >
							<option value=""selected disabled hidden>{{order_item.duration}}</option>
                            {% for obj in duration %}
							<option value="{{ obj.pk }}">{{ obj.name }}</option>
							{% endfor %}
						</select>
                        <input type="submit" value="ok">
					</form>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                Rs{{ order_item.get_discount_item_price }} 
                <span class="badge badge-success" >Saved Rs{{ order_item.get_amount_saved }}</span>
            {% else %}
                Rs{{ order_item.get_total_item_price}}
            {% endif %}
             <a href="{% url 'core:remove-from-cart' order_item.item.pk %}">
                <i class="fas fa-trash float-right text-danger"></i>
             </a>

            </td>
        </tr>

        {% empty %}
        <tr>
            <td colspan="5">Your Cart is Empty</td>
        </tr>

         <tr>
            <td colspan="5">
                <a href="/core" class="btn btn-primary float-right">Continue Shopping</a>
            </td>
        </tr>

        {% endfor %}

        {% if object.get_total_price %}
        {% if object.get_total_price > 0 and object.get_total_price < 1000 %}
        <tr>
            <td colspan="4"><b>Delivery Charge</b></td>
            <td>Rs. 50 </td>
        </tr>        
        {% else %}
        <tr>
            <td colspan="4"><b>Delivery Charge</b></td>
            <td>Rs. 0 </td>
        </tr> 
        
        {% endif %}
        <tr>
            <td colspan="4"><b>Total Order Price</b></td>
            <td>Rs.{{ object.get_total_price }}</td>
        </tr>
         <tr>
            <td colspan="5">
                <a href="{% url 'core:checkout' %}" class="btn btn-warning float-right ml-2">Checkout</a>
                <a href="/core" class="btn btn-primary float-right">Continue Shopping</a>
            </td>
        </tr>
        
        {% endif %}
        
        </tbody>
    </table>

        </div>
    </div>
<!--</main>-->

{% endblock main_content %}

templates/customer_template/sidebar_template.html
{% load cart_template_tags %}
{% load static %}
  <aside class="main-sidebar sidebar-light-red elevation-4">
    <!-- Brand Logo -->
    <a href="" class="brand-link">
      <img src="{% static "dist/img/AdminLTELogo.png" %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-dark">Tiffin Time</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static "dist/img/user2-160x160.jpg" %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{% url 'customer_profile' %}" class="d-block">{{ user.username }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            {% url 'index' as customer_home %}
            <a href="{{ customer_home }}" class="nav-link {% if request.path == customer_home %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Home
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'customer_order_history' as customer_order_history %}
            {% url 'customer_order_information' as customer_order_information %}
            <a href="{{ customer_order_history }}" class="nav-link {% if request.path == customer_order_history %} active {% endif %} {% if request.path == customer_order_information %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                View Orders
              </p>
            </a>
          </li>
           <li class="nav-item">
            {% url 'core:order-summary' as ordersummary %}
            <a href="{% url 'core:order-summary' %}" class="nav-link {% if request.path == ordersummary %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                My Cart
              </p>
            </a>
          </li>
           <li class="nav-item">
            {% url 'customer_feedback' as customer_feedback %}
            <a href="{{ customer_feedback }}" class="nav-link {% if request.path == customer_feedback %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Feedback Message
              </p>
            </a>
          </li>
          
          <li class="nav-item">
            {% url 'customer_all_notification' as customer_all_notification %}
            <a href="{{ customer_all_notification }}" class="nav-link {% if request.path == customer_all_notification %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Notifications
              </p>
            </a>
          </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>